### ISSUE TITLE
Include Dashboard into Radius releases

### ISSUE THREAD

**Issue by willtsai** [radius-project/dashboard#47]
### Overview of feature request

As a Radius user, I want the Radius Dashboard to be packaged into future releases of Radius so that I can install and run the Dashboard with my Radius installs without having to build the dashboard from source.

### Acceptance criteria

1. Dashboard is included into the Radius release process, including: publish/release pipelines, Helm authoring
2. Dashboard is packaged as a part of the Radius release and can be installed along with the Radius control plane
3. User is able to access the Dashboard after they install Radius without having to build dashboard from source

### Additional context

Related:
- https://github.com/radius-project/dashboard/issues/37
- https://github.com/radius-project/dashboard/issues/40

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#11022](https://dev.azure.com/azure-octo/Incubations/_workitems/edit/11022)

**Comment by AaronCrawfis** [comment]
Couple thoughts:

- Installation of the dashboard to your cluster should be configurable via the Helm chart, where you can include the dashboard as part of the installation, or omit it
- When running `rad init` and installing the Radius control-plane via the rad CLI, it should be automatically installed without any prompt/confirmation to the user. That way any downstream deep-linking or commands can assume it's there.
- When installing via the Helm chart directly (`helm install`), we should think through if it should be opt-in or opt-out. My personal vote it opt-in, where a default Helm installation does not install the dashboard, at least for now. It increases the size of the default Radius installation and adds on a security risk for another service that could pose as surface area for attack.
